# Generated by Django 4.0.3 on 2022-04-04 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0003_remove_track_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='artist',
            new_name='user',
        ),
    ]
