# Generated by Django 4.0.3 on 2022-04-05 12:31

from django.db import migrations, models
import tracks.models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0004_rename_artist_track_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=tracks.models.img_upload_location),
        ),
        migrations.AlterField(
            model_name='track',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
