# Generated by Django 4.0.3 on 2022-04-05 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0005_track_image_alter_track_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='image',
            new_name='img_file',
        ),
    ]
