# Generated by Django 4.0.3 on 2022-04-04 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0002_alter_track_audio_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='url',
        ),
    ]
