version: '3.9'

services:
  api:
      build:
        context: ../
        dockerfile: .docker/Dockerfile
      env_file:
        .env
      entrypoint: ["/bin/sh", "-c"]
      command:
        - |
          python manage.py makemigrations
          python manage.py migrate
          python manage.py runserver 0.0.0.0:8000
      ports:
        - "8080:8000"
      depends_on:
        db:
          condition: service_healthy

  db:
    image: postgres:14
    container_name: ${DB_HOST}
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 30s
      retries: 6
    restart: always
